In [1]:
print("Helloo")

Helloo


In [2]:
print("hello")

hello


In [4]:
type([1,2,3,])

list

In [6]:
import numpy as np

In [7]:
a=[1,2,3,]

In [10]:
b=np.array(a)
type(a)

list

In [11]:
b=np.array([1,2,3])
type(b)

numpy.ndarray

In [15]:
a=np.array(2,1)

TypeError: Cannot interpret '1' as a data type

In [16]:
a.ndim


1

In [20]:
n=[[12,34,45,56],[12,13,14]]
type(n)

list

In [21]:
b.ndim

1

In [25]:
x=np.array(b)
print(x)

[1 2 3]


In [26]:
b.shape

(3,)

In [28]:
x.shape

(3,)

In [29]:
b.size

3

In [30]:
b.itemsize

8

In [31]:
b.data

In [32]:
b.dtype

dtype('int64')

In [36]:
t=[[10,11,12,13],[1,11,
                  2,3]]
type(t)

list

In [38]:
b.shape

(3,)

In [39]:
d=np.array(t)
type(d)

numpy.ndarray

In [40]:
d.shape

(2, 4)

In [41]:
d.size

8

In [42]:
d.ndim

2

In [43]:
d.dtype

dtype('int64')

In [44]:
d.data

In [49]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [54]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])