In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
b=np.array([(1,2,3,4),(7,8,9,10)])
b

array([[ 1,  2,  3,  4],
       [ 7,  8,  9, 10]])

In [4]:
b.dtype

dtype('int64')

In [5]:
a.dtype

dtype('int64')

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.zeros((3,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [14]:
b.size


8

In [15]:
a.size

4

In [16]:
b.dtype

dtype('int64')

In [17]:
a.dtype

dtype('int64')

In [18]:
b.data

In [19]:
b.shape

(2, 4)

In [20]:
#oprations
np.copy(a)

array([1, 2, 3, 4])

In [34]:
#sorting

In [38]:
a.sort()
a

array([1, 2, 3, 4])

In [40]:
a.sort(axis=0)
a

array([1, 2, 3, 4])

In [55]:
a

array([1, 2, 3, 4])

In [62]:
a.view(dtype="float")

array([4.9e-324, 9.9e-324, 1.5e-323, 2.0e-323])

In [56]:
z=a.reshape((4,1))
z

array([[1],
       [2],
       [3],
       [4]])

In [58]:
np.copy(a)

array([1, 2, 3, 4])

In [64]:
np.copy(a)

array([1, 2, 3, 4])

In [67]:
#adding
np.append(a,5)

array([1, 2, 3, 4, 5])

In [73]:
np.insert(a,4,6)

array([1, 2, 3, 4, 6])

In [74]:
n=np.array([10,11,12])
n

array([10, 11, 12])

In [75]:
#removing
np.delete(n,2,axis=0)

array([10, 11])

In [82]:
np.delete(n,2,axis=0)

array([10, 11])

In [83]:
n

array([10, 11, 12])

In [86]:
d=np.delete(n,1)

In [87]:
d

array([10, 12])

In [88]:
d

array([10, 12])

In [96]:
d=np.delete(n,1,axis=0)

In [93]:
d

array([11, 12])

In [94]:
d

array([11, 12])

In [97]:
d

array([10, 12])

In [100]:
s=np.delete(n,0)
d

array([11, 12])

In [102]:
t=np.delete(n,0)
t

array([11, 12])

In [104]:
r=np.delete(n,1)
r

array([10, 12])

In [106]:
np.delete(n,2)

array([10, 11])

In [109]:
#combining
np.concatenate((n,a),axis=0)

array([10, 11, 12,  1,  2,  3,  4])

In [111]:
np.concatenate((n,a),axis=0)

array([10, 11, 12,  1,  2,  3,  4])

In [114]:
#Splitting:
np.split(a,4)

[array([1]), array([2]), array([3]), array([4])]

In [115]:
np.split(n,3)

[array([10]), array([11]), array([12])]

In [123]:
#Indexing:
a[3]=7
a

array([5, 5, 6, 7])

In [130]:
#Subseting
a[2]

6

In [133]:
a[3]

7