In [1]:
import numpy as np

In [7]:
a=np.array([1,2,3,4,5])
b=np.array([[11,12,13,14]])
a

array([1, 2, 3, 4, 5])

In [3]:
b

array([11, 12, 13, 14, 15])

In [15]:
c=np.hstack(a,b)

NameError: name 'c' is not defined

In [19]:
a=np.arange(2,5,2)
a

array([2, 4])

In [40]:
n=np.array([(1,2,3),(4,5,6)])
n

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
n[1:2]

array([[2, 3, 4]])

In [30]:
n[0:1]

array([[1, 2, 3]])

In [31]:
n[:,2]

array([3, 4])

In [38]:
n[1:0]

array([], shape=(0, 3), dtype=int64)

In [44]:
n[0:,2]

array([3, 6])

In [46]:
arr=np.random.normal(5,50,10)
arr

array([ 57.73646131, -24.31951751, -11.70144823, 105.58937934,
         2.38694094,  18.78440651, -15.53844303, 118.97583947,
        32.50200899, -65.22478919])

In [47]:
arr=np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
arr=np.random.randint(0,10, size=(3,2))
arr.shape

(3, 2)

In [51]:
arr=np.random.randint(0,10, size=(3,2))
arr

array([[0, 4],
       [9, 2],
       [8, 6]])

In [55]:
arr+=5
arr

array([[10, 14],
       [19, 12],
       [18, 16]])

In [56]:
b+=5
b

array([16, 17, 18, 19])

In [58]:
arr=np.random.randint(0,10,size=(3,3))
print(arr)
print(arr.max())

[[7 1 5]
 [9 0 5]
 [6 4 6]]
9


In [62]:
arr=np.random.randint(0,10,size=(3,3))
print(arr)
print(arr.sum())

[[8 8 3]
 [2 9 3]
 [2 3 8]]
46


In [63]:
arr=np.random.randint(0,10,size=(3,3))
print(arr)
print(arr.shape)
print("After Reshape")
arr=arr.reshape(9,1)
print(arr)

[[1 2 7]
 [4 2 4]
 [1 8 6]]
(3, 3)
After Reshape
[[1]
 [2]
 [7]
 [4]
 [2]
 [4]
 [1]
 [8]
 [6]]


In [64]:
x=([1,2,3])
y=([1,2,3])
x,y

([1, 2, 3], [1, 2, 3])

In [66]:
c=x+y
c

[1, 2, 3, 1, 2, 3]

In [74]:
c=np.add(x,y)
print(c)

[2 4 6]


In [78]:
arr=np.random.randint(0,10,size=(3,3))
print("Swap")
arr=arr.T
print(arr)

Swap
[[5 4 8]
 [7 1 0]
 [4 0 7]]
